### ISSUE TITLE
Error: callback already called

### ISSUE THREAD

**Issue by joergd** [spion/genny#3]
I've tried this all day and don't know why this error gets thrown. This is the code, and the console output:

    var genny = require('genny')

    require('dotenv').load({path: '../.env'})

    var stripe = require("stripe")(process.env.STRIPE_API_KEY)

    fetchCharges = genny.fn(function* (d) {
      console.log("Fetching charges")
      var charges = yield fetchList(d())
      console.log("End of fetching charges", charges.length)
      return true
    })

    fetchList = genny.fn(function* (done) {
      console.log("fetchList")

      var results = yield stripe.charges.list({
        limit: process.env.STRIPE_CURSOR_LIMIT,
        "include[]": 'total_count'
      }, done())

      console.log("Got first page of charges")
      return results.data
    })

    genny.run(function* (resume) {
      console.log('before')
      yield fetchCharges(resume())
      console.log('after')
    })

And the console ...

    > node --harmony genny.js

    before 
    Fetching charges
    fetchList
    Got first page of charges
    End of fetching charges 100
    after
    /Volumes/dev/stripe-ingest/node_modules/genny/index.js:50
        else throw e; 
    ....
    at /Volumes/dev/zebra/zebra/stripe-ingest/genny.js:29:26

It works fine if fetchList is

    fetchList = genny.fn(function* (done) {
      console.log("fetchList")

      yield setTimeout(done(), 1000);

      console.log("Got first page of charges")
      return []
    })

I just can't figure out why the fetchCharges iterator is doing an additional next() to cause the error ...

UPDATE: It is because the Stripe nodejs API also returns a Promise, the callback is optional. So both the callback and the promise are next()ing the iterator.

**Comment by spion** [comment]
Sorry, I haven't had much time lately to look at this, but if the API returns a promise its probably better not to use `resume()` at all

**Comment by radford** [comment]
@joergd, I'm going to assume this is fixed by my recent update.  reopen if this is not the case.
