### ISSUE TITLE
Throwing an error in nested genny.fn() causes the error to be incorrectly reported as "Generator is already running"

### ISSUE THREAD

**Issue by joergd** [spion/genny#4]
var genny = require('genny')

    var child = genny.fn(function* (resume) {
      throw(new Error)
    })

    var parent = genny.fn(function* (resume){
      return yield child(resume())
    })

    genny.run(function* (resume) {
      console.log('Start')
      yield parent(resume())
      console.log('Finish')
    }, function(err) {
      console.log(err)
    })

And the console output is:

    > node --harmony fail.js

    Start
    [Error: Generator is already running]

**Comment by radford** [comment]
@joergd, I have a fix this (my here? radford/genny@a22653f) along with many others, but I haven't had time to push them upstream since my version has diverged quite a bit.

**Comment by spion** [comment]
@radford is the fork backward-compatible? If so, I'd be interested in merging it.

Since I wrote the library I'm working somewhere else so I haven't had much time to maintain it. Therefore I added you as a collaborator :)

**Comment by radford** [comment]
Thanks @spion.  There are a few incompatible changes.  One is radford/genny@7a8a37d drop 'yield resume' support.  The other is dropping support for the old generator `.send()` method in radford/genny@95b88b2.  If you're OK with these, then I'd be happy to merge my branch.

**Comment by spion** [comment]
The second one definitely, but I'm not entirely sure about the first - there might be users that take advantage of it. Should be fine if we bump the version though. Perhaps even as high as 1.0 as it seems that your version is quite stable. 

The way you resolved the issue with immediate `resume()` by clearing `complete` before running the iterator then going again if its been filled up is just brilliant :)

**Comment by radford** [comment]
Thanks, @spion! It just took me a while to re-figure it out myself.

I removed `yield resume` support because it seemed like the cost in code was not worth the benefit to the API.  I think it can be reimplemented without the need for the `WorkQueue` by passing an incremented integer third argument to `createResumer` and stashing the result in an array at that index, but I never took the time to work out the details.

I think bumping the version number and releasing is the best way forward since the bugs are worse than the missing feature.  @joergd, can you confirm you don't use said `yield resume` feature?

**Comment by joergd** [comment]
Hey @radford - no - I do use yield resume, but it's fine - I'll use yield [] instead. So go for it.

**Comment by spion** [comment]
Awesome, feel free to merge and bump to 1.0 :)

**Comment by radford** [comment]
@spion, I ended up re-implementing `yield resume` support on my branch and merging it into `spion/master`.  Because this keeps the interface backwards compatible, I just bumped the version to 0.5.6.  @joergd, would you mind testing this to see if it fixes this issue?

**Comment by joergd** [comment]
Hey @radford - yes working fine now - thanks!

**Comment by skyblue** [comment]
Great lib!  help me a lot!

**Comment by spion** [comment]
Awesomeness. I published the new version yesterday. @joergd can you check if it fixes your issues?

**Comment by heavyk** [comment]
absolute awesomeness! yield [] is waaayy more intuitive! really really cool thanks so much
