### ISSUE TITLE
Bluebird warning when yielding on second promise

### ISSUE THREAD

**Issue by deaks-kt** [spion/genny#7]
Found something odd in v0.5.6 whilst working with Sequelize.  It was kicking out the following warnings in my development environment:

`Warning: a promise was created in a handler but was not returned from it`

After a little playing around I found I could replicate it by simply yielding on a second bluebird promise inside a generator. e.g.:

```
var genny = require('genny');
var bluebird = require('bluebird');

function* generator1(resume) {
    var then = new Date();    
    yield bluebird.delay(200);
    console.log('duration: %s ms', (new Date() - then));
    yield bluebird.delay(200);
    console.log('duration: %s ms', (new Date() - then));
}

genny.run(generator1);
```

When running the above with `NODE_ENV=development node` I get the following ouput:

```
duration: 205 ms
Warning: a promise was created in a handler but was not returned from it
    at Timer.listOnTimeout (timers.js:92:15)

duration: 420 ms
```

If I just yield on the first promise, or chain the promises outside the generator, no warnings are issued.  

I am going to dig a little myself, but I am somewhat new to Node and JS, so thought I'd throw it out there first :)

Nice module BTW... I found this one the easiest to get my head around...

**Comment by deaks-kt** [comment]
After reviewing the Bluebird warning info, it seems to be due to the fact there is no Promise returned in the `.then()` of `handlePromise()`.  I just added a `return null` and it suppresses the warning:

```
function handlePromise(promise, handler) {
    promise.then(function promiseSuccess(result) {
        handler(null, result);
        return null;
    }, function promiseError(err) {
        handler(err);
    });
}
```

Does this look like a viable fix or have I overlooked something?  It seems strange that it's the second yield that triggers the warning and not the first...

**Comment by spion** [comment]
As far as I know, latest bluebird should not trigger this warning any longer.

**Comment by deaks-kt** [comment]
Yes, just confirmed with `bluebird@3.3.4`

Thank you!  Just need to update Sequelize now.
